from yuno_bot.domain_modules.chest.admin import (
    add_chest,
    add_item,
    audit_log,
    chest_access,
    chest_detail,
    chest_items,
    chest_settings,
    chest_stock,
    edit_chest,
    publish_chest,
    recover_chest,
    select_chest,
    set_chest_admin_roles,
    set_chest_deposit_roles,
    set_chest_log_channel,
    set_chest_panel_channel,
    set_chest_view_roles,
    set_chest_withdraw_roles,
    toggle_chest_balances,
    toggle_chest_history,
    toggle_chest_reason,
    toggle_chest_item,
    configure,
    diagnose,
    edit_texts,
    inventory,
    link_items,
    manage_chests,
    manage_items,
    open_access,
    publish_catalog,
    recover,
    render_admin,
    set_log_channel,
    set_operator_roles,
    set_panel_channel,
    toggle_balances,
    toggle_history,
    toggle_reason,
)
from yuno_bot.domain_modules.chest.runtime import (
    deliver_log,
    deliver_panel,
    handle_resource_delete,
    run_job,
    startup,
)
from yuno_bot.domain_modules.chest.ui import (
    chests_next,
    chests_prev,
    deposit,
    deposit_cancel,
    deposit_confirm,
    deposit_item,
    deposit_next,
    deposit_prev,
    deposit_submit,
    history_own,
    own_history_owner,
    render_chest,
    view_stock,
    withdraw,
    withdraw_cancel,
    withdraw_confirm,
    withdraw_item,
    withdraw_next,
    withdraw_prev,
    withdraw_submit,
)
from yuno_bot.platform.contracts import (
    ActionDefinition,
    AdminActionDefinition,
    AdminPageDefinition,
    DeliveryRendererDefinition,
    JobHandlerDefinition,
    ModuleUIAdapter,
    PanelDefinition,
)

MODULE_UI = ModuleUIAdapter(
    module_key="chest",
    contract_version=1,
    name="Sistema de Bau",
    description="Catalogo versionado, estoque e ledger imutavel.",
    icon="📦",
    order=35,
    minimum_plan="basico",
    admin_pages=(AdminPageDefinition("overview", render_admin),),
    admin_actions=(
        AdminActionDefinition("inventory", inventory),
        AdminActionDefinition("select_chest", select_chest),
        AdminActionDefinition("add_chest", add_chest),
        AdminActionDefinition("add_item", add_item),
        AdminActionDefinition("chest_detail", chest_detail),
        AdminActionDefinition("chest_items", chest_items),
        AdminActionDefinition("toggle_chest_item", toggle_chest_item),
        AdminActionDefinition("chest_stock", chest_stock),
        AdminActionDefinition("chest_access", chest_access),
        AdminActionDefinition("set_chest_view_roles", set_chest_view_roles),
        AdminActionDefinition("set_chest_deposit_roles", set_chest_deposit_roles),
        AdminActionDefinition("set_chest_withdraw_roles", set_chest_withdraw_roles),
        AdminActionDefinition("set_chest_admin_roles", set_chest_admin_roles),
        AdminActionDefinition("chest_settings", chest_settings),
        AdminActionDefinition("set_chest_panel_channel", set_chest_panel_channel),
        AdminActionDefinition("set_chest_log_channel", set_chest_log_channel),
        AdminActionDefinition("toggle_chest_balances", toggle_chest_balances),
        AdminActionDefinition("toggle_chest_history", toggle_chest_history),
        AdminActionDefinition("toggle_chest_reason", toggle_chest_reason),
        AdminActionDefinition("edit_chest", edit_chest),
        AdminActionDefinition("publish_chest", publish_chest),
        AdminActionDefinition("recover_chest", recover_chest),
        AdminActionDefinition("diagnose", diagnose),
        AdminActionDefinition("audit", audit_log),
    ),
    panels=(
        PanelDefinition(
            "chest", render_chest, version=1, recovery_policy="automatic"
        ),
    ),
    actions=(
        ActionDefinition(
            "view_stock", "chest", "chest.view", view_stock, panel_key="chest"
        ),
        ActionDefinition(
            "deposit", "chest", "chest.deposit", deposit, panel_key="chest"
        ),
        ActionDefinition(
            "deposit_prev", "chest", "chest.deposit", deposit_prev, panel_key="chest"
        ),
        ActionDefinition(
            "deposit_next", "chest", "chest.deposit", deposit_next, panel_key="chest"
        ),
        ActionDefinition(
            "deposit_item", "chest", "chest.deposit", deposit_item, panel_key="chest"
        ),
        ActionDefinition(
            "deposit_submit",
            "chest",
            "chest.deposit",
            deposit_submit,
            panel_key="chest",
        ),
        ActionDefinition(
            "deposit_confirm",
            "chest",
            "chest.deposit",
            deposit_confirm,
            panel_key="chest",
        ),
        ActionDefinition(
            "deposit_cancel",
            "chest",
            "chest.deposit",
            deposit_cancel,
            panel_key="chest",
        ),
        ActionDefinition(
            "withdraw", "chest", "chest.withdraw", withdraw, panel_key="chest"
        ),
        ActionDefinition(
            "withdraw_prev",
            "chest",
            "chest.withdraw",
            withdraw_prev,
            panel_key="chest",
        ),
        ActionDefinition(
            "withdraw_next",
            "chest",
            "chest.withdraw",
            withdraw_next,
            panel_key="chest",
        ),
        ActionDefinition(
            "withdraw_item",
            "chest",
            "chest.withdraw",
            withdraw_item,
            panel_key="chest",
        ),
        ActionDefinition(
            "withdraw_submit",
            "chest",
            "chest.withdraw",
            withdraw_submit,
            panel_key="chest",
        ),
        ActionDefinition(
            "withdraw_confirm",
            "chest",
            "chest.withdraw",
            withdraw_confirm,
            panel_key="chest",
        ),
        ActionDefinition(
            "withdraw_cancel",
            "chest",
            "chest.withdraw",
            withdraw_cancel,
            panel_key="chest",
        ),
        ActionDefinition(
            "history_own",
            "chest",
            "chest.history_own",
            history_own,
            panel_key="chest",
            resource_owner_resolver=own_history_owner,
        ),
    ),
    jobs=(JobHandlerDefinition("chest.panel.reconcile", run_job),),
    deliveries=(
        DeliveryRendererDefinition("chest.panel", deliver_panel),
        DeliveryRendererDefinition("chest.log", deliver_log),
    ),
    startup_handler=startup,
    resource_delete_handler=handle_resource_delete,
)

__all__ = ["MODULE_UI"]
