from yuno_bot.domain_modules.tags.ui import (
    add_binding,
    back,
    cancel_run,
    cleanup,
    confirm_cleanup,
    confirm_publish,
    diagnostics,
    diagnose_member,
    manage_binding,
    open_system,
    page_next,
    page_prev,
    preview,
    render_admin,
    run_job,
    sync,
    toggle_lifecycle,
)
from yuno_bot.platform.contracts import AdminActionDefinition, AdminPageDefinition, JobHandlerDefinition, ModuleUIAdapter


MODULE_UI = ModuleUIAdapter(
    module_key="tags",
    contract_version=1,
    name="Sistema de Tags",
    description="Tags por cargo com prioridade baseada na hierarquia ao vivo.",
    icon="🏷️",
    order=20,
    minimum_plan="basico",
    admin_pages=(AdminPageDefinition("overview", render_admin),),
    admin_actions=(
        AdminActionDefinition("open_system", open_system),
        AdminActionDefinition("page_prev", page_prev),
        AdminActionDefinition("page_next", page_next),
        AdminActionDefinition("back", back),
        AdminActionDefinition("add_binding", add_binding),
        AdminActionDefinition("manage_binding", manage_binding),
        AdminActionDefinition("preview", preview),
        AdminActionDefinition("confirm_publish", confirm_publish),
        AdminActionDefinition("toggle_lifecycle", toggle_lifecycle),
        AdminActionDefinition("sync", sync),
        AdminActionDefinition("cancel_run", cancel_run),
        AdminActionDefinition("cleanup", cleanup),
        AdminActionDefinition("confirm_cleanup", confirm_cleanup),
        AdminActionDefinition("diagnostics", diagnostics),
        AdminActionDefinition("diagnose_member", diagnose_member),
    ),
    jobs=(
        JobHandlerDefinition("tags.member.sync", run_job),
        JobHandlerDefinition("tags.run.plan", run_job),
        JobHandlerDefinition("tags.run.finalize", run_job),
        JobHandlerDefinition("tags.retention", run_job),
    ),
)
