from yuno_bot.domain_modules.bau.ui import (
    add_category,
    add_item,
    clear_stock_confirm,
    clear_stock_execute,
    confirm_publish,
    deliver_log,
    edit_category,
    edit_item,
    open_system,
    render_admin,
    render_stock,
    review_publish,
    run_job,
    select_category,
    set_log_channel,
    set_panel_channel,
    set_staff_roles,
    submit_movement,
)
from yuno_bot.platform.contracts import (
    ActionDefinition,
    AdminActionDefinition,
    AdminPageDefinition,
    DeliveryRendererDefinition,
    JobHandlerDefinition,
    ModuleUIAdapter,
    PanelDefinition,
)

MODULE_UI = ModuleUIAdapter(
    module_key="bau",
    contract_version=1,
    name="Baú da Gerência",
    description="Controle de inventário e estoque compartilhado da organização.",
    icon="📦",
    order=65,
    minimum_plan="basico",
    admin_pages=(AdminPageDefinition("overview", render_admin),),
    admin_actions=(
        AdminActionDefinition("open_system", open_system),
        AdminActionDefinition("set_panel_channel", set_panel_channel),
        AdminActionDefinition("set_log_channel", set_log_channel),
        AdminActionDefinition("set_staff_roles", set_staff_roles),
        AdminActionDefinition("add_category", add_category),
        AdminActionDefinition("edit_category", edit_category),
        AdminActionDefinition("add_item", add_item),
        AdminActionDefinition("edit_item", edit_item),
        AdminActionDefinition("clear_stock_confirm", clear_stock_confirm),
        AdminActionDefinition("clear_stock_execute", clear_stock_execute),
        AdminActionDefinition("review_publish", review_publish),
        AdminActionDefinition("confirm_publish", confirm_publish),
    ),
    panels=(PanelDefinition("stock", render_stock, recovery_policy="automatic"),),
    actions=(
        ActionDefinition("select_category", "stock", "bau.move_stock", select_category, panel_key="stock"),
        ActionDefinition("submit_movement", "stock", "bau.move_stock", submit_movement, panel_key="stock"),
    ),
    jobs=(JobHandlerDefinition("bau.panel.reconcile", run_job),),
    deliveries=(DeliveryRendererDefinition("bau.log", deliver_log),),
)
