"""add parceria tables

Revision ID: 3795707f5b0a
Revises: d4b265e2fb2a
Create Date: 2026-07-29 17:30:07.940419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3795707f5b0a'
down_revision: Union[str, Sequence[str], None] = 'd4b265e2fb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parceria_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('registrar_channel_id', sa.String(length=32), nullable=False),
    sa.Column('ativas_channel_id', sa.String(length=32), nullable=False),
    sa.Column('panel_message_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parceria_configs_guild_id'), 'parceria_configs', ['guild_id'], unique=True)
    op.create_table('parcerias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('nome_familia', sa.String(length=100), nullable=False),
    sa.Column('nome_familia_normalizado', sa.String(length=100), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=False),
    sa.Column('contato_01', sa.String(length=150), nullable=True),
    sa.Column('contato_02', sa.String(length=150), nullable=True),
    sa.Column('mensagem_lista_id', sa.String(length=32), nullable=False),
    sa.Column('nome_arquivo_imagem', sa.String(length=255), nullable=False),
    sa.Column('registrado_por', sa.String(length=32), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'nome_familia_normalizado', name='uq_parcerias_guild_nome')
    )
    op.create_index(op.f('ix_parcerias_ativo'), 'parcerias', ['ativo'], unique=False)
    op.create_index(op.f('ix_parcerias_guild_id'), 'parcerias', ['guild_id'], unique=False)
    op.create_index(op.f('ix_parcerias_nome_familia_normalizado'), 'parcerias', ['nome_familia_normalizado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcerias_nome_familia_normalizado'), table_name='parcerias')
    op.drop_index(op.f('ix_parcerias_guild_id'), table_name='parcerias')
    op.drop_index(op.f('ix_parcerias_ativo'), table_name='parcerias')
    op.drop_table('parcerias')
    op.drop_index(op.f('ix_parceria_configs_guild_id'), table_name='parceria_configs')
    op.drop_table('parceria_configs')
    # ### end Alembic commands ###
