"""baseline schema

Revision ID: b83c59e0158e
Revises: 
Create Date: 2026-07-29 17:16:13.228148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b83c59e0158e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_guild_id'), 'audit_logs', ['guild_id'], unique=False)
    op.create_table('ausencias',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avisado', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_index(op.f('ix_ausencias_avisado'), 'ausencias', ['avisado'], unique=False)
    op.create_index(op.f('ix_ausencias_fim'), 'ausencias', ['fim'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_discord_user_id'), 'customers', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('farm_ticket_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('category_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('admin_role_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('log_channel_id', sa.String(length=32), nullable=False),
    sa.Column('panel_channel_id', sa.String(length=32), nullable=False),
    sa.Column('folders_category_id', sa.String(length=32), nullable=True),
    sa.Column('participant_role_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_ticket_configs_guild_id'), 'farm_ticket_configs', ['guild_id'], unique=True)
    op.create_table('farm_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('week_id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('member_name', sa.String(length=120), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('panel_message_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=32), nullable=True),
    sa.Column('goal_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.String(length=32), nullable=True),
    sa.Column('finalization_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_tickets_assigned_to'), 'farm_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_farm_tickets_channel_id'), 'farm_tickets', ['channel_id'], unique=False)
    op.create_index(op.f('ix_farm_tickets_created_at'), 'farm_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_tickets_guild_id'), 'farm_tickets', ['guild_id'], unique=False)
    op.create_index(op.f('ix_farm_tickets_status'), 'farm_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_farm_tickets_user_id'), 'farm_tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_farm_tickets_week_id'), 'farm_tickets', ['week_id'], unique=False)
    op.create_table('farm_weekly_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('week_id', sa.String(length=12), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'week_id', name='uq_farm_weekly_goal_guild_week')
    )
    op.create_index(op.f('ix_farm_weekly_goals_active'), 'farm_weekly_goals', ['active'], unique=False)
    op.create_index(op.f('ix_farm_weekly_goals_guild_id'), 'farm_weekly_goals', ['guild_id'], unique=False)
    op.create_index(op.f('ix_farm_weekly_goals_week_id'), 'farm_weekly_goals', ['week_id'], unique=False)
    op.create_table('guild_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('guild_name', sa.String(length=120), nullable=True),
    sa.Column('admin_role_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('log_channel_id', sa.String(length=32), nullable=True),
    sa.Column('modules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('command_permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_configs_guild_id'), 'guild_configs', ['guild_id'], unique=True)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_provider'), 'payment_events', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_events_reference'), 'payment_events', ['reference'], unique=True)
    op.create_index(op.f('ix_payment_events_status'), 'payment_events', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_products_guild_name')
    )
    op.create_index(op.f('ix_products_guild_id'), 'products', ['guild_id'], unique=False)
    op.create_table('system_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'open', 'in_progress', 'done', 'cancelled', name='recordstatus'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('requester_id', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=32), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_records_channel_id'), 'system_records', ['channel_id'], unique=False)
    op.create_index(op.f('ix_system_records_created_at'), 'system_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_records_guild_id'), 'system_records', ['guild_id'], unique=False)
    op.create_index(op.f('ix_system_records_module'), 'system_records', ['module'], unique=False)
    op.create_index(op.f('ix_system_records_requester_id'), 'system_records', ['requester_id'], unique=False)
    op.create_index(op.f('ix_system_records_reviewer_id'), 'system_records', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_system_records_status'), 'system_records', ['status'], unique=False)
    op.create_table('farm_ticket_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('event_id', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('log_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_message_id', sa.String(length=32), nullable=True),
    sa.Column('log_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['farm_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_ticket_actions_action'), 'farm_ticket_actions', ['action'], unique=False)
    op.create_index(op.f('ix_farm_ticket_actions_actor_id'), 'farm_ticket_actions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_farm_ticket_actions_created_at'), 'farm_ticket_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_ticket_actions_event_id'), 'farm_ticket_actions', ['event_id'], unique=False)
    op.create_index(op.f('ix_farm_ticket_actions_guild_id'), 'farm_ticket_actions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_farm_ticket_actions_ticket_id'), 'farm_ticket_actions', ['ticket_id'], unique=False)
    op.create_table('farm_ticket_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('proof_channel_id', sa.String(length=32), nullable=False),
    sa.Column('proof_message_id', sa.String(length=32), nullable=False),
    sa.Column('proof_url', sa.Text(), nullable=False),
    sa.Column('log_proof_url', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['farm_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_ticket_entries_created_at'), 'farm_ticket_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_ticket_entries_guild_id'), 'farm_ticket_entries', ['guild_id'], unique=False)
    op.create_index(op.f('ix_farm_ticket_entries_status'), 'farm_ticket_entries', ['status'], unique=False)
    op.create_index(op.f('ix_farm_ticket_entries_ticket_id'), 'farm_ticket_entries', ['ticket_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'blocked', 'revoked', name='licensestatus'), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=True),
    sa.Column('guild_name', sa.String(length=120), nullable=True),
    sa.Column('owner_discord_id', sa.String(length=32), nullable=True),
    sa.Column('payment_provider', sa.String(length=40), nullable=True),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_licenses_key'), 'licenses', ['key'], unique=True)
    op.create_index(op.f('ix_licenses_owner_discord_id'), 'licenses', ['owner_discord_id'], unique=False)
    op.create_index(op.f('ix_licenses_status'), 'licenses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_status'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_owner_discord_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_key'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_farm_ticket_entries_ticket_id'), table_name='farm_ticket_entries')
    op.drop_index(op.f('ix_farm_ticket_entries_status'), table_name='farm_ticket_entries')
    op.drop_index(op.f('ix_farm_ticket_entries_guild_id'), table_name='farm_ticket_entries')
    op.drop_index(op.f('ix_farm_ticket_entries_created_at'), table_name='farm_ticket_entries')
    op.drop_table('farm_ticket_entries')
    op.drop_index(op.f('ix_farm_ticket_actions_ticket_id'), table_name='farm_ticket_actions')
    op.drop_index(op.f('ix_farm_ticket_actions_guild_id'), table_name='farm_ticket_actions')
    op.drop_index(op.f('ix_farm_ticket_actions_event_id'), table_name='farm_ticket_actions')
    op.drop_index(op.f('ix_farm_ticket_actions_created_at'), table_name='farm_ticket_actions')
    op.drop_index(op.f('ix_farm_ticket_actions_actor_id'), table_name='farm_ticket_actions')
    op.drop_index(op.f('ix_farm_ticket_actions_action'), table_name='farm_ticket_actions')
    op.drop_table('farm_ticket_actions')
    op.drop_index(op.f('ix_system_records_status'), table_name='system_records')
    op.drop_index(op.f('ix_system_records_reviewer_id'), table_name='system_records')
    op.drop_index(op.f('ix_system_records_requester_id'), table_name='system_records')
    op.drop_index(op.f('ix_system_records_module'), table_name='system_records')
    op.drop_index(op.f('ix_system_records_guild_id'), table_name='system_records')
    op.drop_index(op.f('ix_system_records_created_at'), table_name='system_records')
    op.drop_index(op.f('ix_system_records_channel_id'), table_name='system_records')
    op.drop_table('system_records')
    op.drop_index(op.f('ix_products_guild_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_events_status'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_reference'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_provider'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_guild_configs_guild_id'), table_name='guild_configs')
    op.drop_table('guild_configs')
    op.drop_index(op.f('ix_farm_weekly_goals_week_id'), table_name='farm_weekly_goals')
    op.drop_index(op.f('ix_farm_weekly_goals_guild_id'), table_name='farm_weekly_goals')
    op.drop_index(op.f('ix_farm_weekly_goals_active'), table_name='farm_weekly_goals')
    op.drop_table('farm_weekly_goals')
    op.drop_index(op.f('ix_farm_tickets_week_id'), table_name='farm_tickets')
    op.drop_index(op.f('ix_farm_tickets_user_id'), table_name='farm_tickets')
    op.drop_index(op.f('ix_farm_tickets_status'), table_name='farm_tickets')
    op.drop_index(op.f('ix_farm_tickets_guild_id'), table_name='farm_tickets')
    op.drop_index(op.f('ix_farm_tickets_created_at'), table_name='farm_tickets')
    op.drop_index(op.f('ix_farm_tickets_channel_id'), table_name='farm_tickets')
    op.drop_index(op.f('ix_farm_tickets_assigned_to'), table_name='farm_tickets')
    op.drop_table('farm_tickets')
    op.drop_index(op.f('ix_farm_ticket_configs_guild_id'), table_name='farm_ticket_configs')
    op.drop_table('farm_ticket_configs')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_discord_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_ausencias_fim'), table_name='ausencias')
    op.drop_index(op.f('ix_ausencias_avisado'), table_name='ausencias')
    op.drop_table('ausencias')
    op.drop_index(op.f('ix_audit_logs_guild_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
