"""add member folder columns to farm tickets

Revision ID: d4b265e2fb2a
Revises: b83c59e0158e
Create Date: 2026-07-29 17:18:42.899115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b265e2fb2a'
down_revision: Union[str, Sequence[str], None] = 'b83c59e0158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_tickets', sa.Column('folder_channel_id', sa.String(length=32), nullable=True))
    op.add_column('farm_tickets', sa.Column('folder_slot', sa.Integer(), nullable=True))
    op.add_column('farm_tickets', sa.Column('game_id', sa.String(length=32), nullable=True))
    op.add_column('farm_tickets', sa.Column('folder_nickname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_tickets', 'folder_nickname')
    op.drop_column('farm_tickets', 'game_id')
    op.drop_column('farm_tickets', 'folder_slot')
    op.drop_column('farm_tickets', 'folder_channel_id')
    # ### end Alembic commands ###
