from yuno_bot.domain_modules.registration.ui import (
    add_approvers,
    approve,
    confirm_publish,
    deliver_dm,
    deliver_log,
    deliver_review,
    edit_errors,
    edit_messages,
    edit_panel,
    edit_rules,
    edit_system,
    edit_team,
    open_form,
    open_system,
    reject,
    remove_approvers,
    render_admin,
    render_public,
    render_review,
    review_publish,
    run_job,
    section,
    set_approval_channel,
    set_log_channel,
    set_member_role,
    set_panel_color,
    set_panel_channel,
    set_flags,
    submit,
    submit_rejection,
)
from yuno_bot.platform.contracts import (
    ActionDefinition,
    AdminActionDefinition,
    AdminPageDefinition,
    DeliveryRendererDefinition,
    JobHandlerDefinition,
    ModuleUIAdapter,
    PanelDefinition,
)


MODULE_UI = ModuleUIAdapter(
    module_key="registration",
    contract_version=1,
    name="Registro",
    description="Registro de membros com aprovacao segura.",
    icon="📝",
    order=10,
    minimum_plan="basico",
    admin_pages=(AdminPageDefinition("overview", render_admin),),
    admin_actions=(
        AdminActionDefinition("open_system", open_system),
        AdminActionDefinition("section", section),
        AdminActionDefinition("set_panel_channel", set_panel_channel),
        AdminActionDefinition("set_approval_channel", set_approval_channel),
        AdminActionDefinition("set_log_channel", set_log_channel),
        AdminActionDefinition("set_member_role", set_member_role),
        AdminActionDefinition("set_panel_color", set_panel_color),
        AdminActionDefinition("add_approvers", add_approvers),
        AdminActionDefinition("remove_approvers", remove_approvers),
        AdminActionDefinition("set_flags", set_flags),
        AdminActionDefinition("edit_system", edit_system),
        AdminActionDefinition("edit_team", edit_team),
        AdminActionDefinition("edit_rules", edit_rules),
        AdminActionDefinition("edit_panel", edit_panel),
        AdminActionDefinition("edit_messages", edit_messages),
        AdminActionDefinition("edit_errors", edit_errors),
        AdminActionDefinition("review_publish", review_publish),
        AdminActionDefinition("confirm_publish", confirm_publish),
    ),
    panels=(
        PanelDefinition("public", render_public, recovery_policy="automatic"),
        PanelDefinition("review", render_review, recovery_policy="automatic"),
    ),
    actions=(
        ActionDefinition("open_form", "public", "registration.submit", open_form, panel_key="public"),
        ActionDefinition("submit", "public", "registration.submit", submit, panel_key="public"),
        ActionDefinition("approve", "review", "registration.review", approve, panel_key="review"),
        ActionDefinition("reject", "review", "registration.review", reject, panel_key="review"),
        ActionDefinition("submit_rejection", "review", "registration.review", submit_rejection, panel_key="review"),
    ),
    jobs=(
        JobHandlerDefinition("registration.processing.recover", run_job),
        JobHandlerDefinition("registration.panel.reconcile", run_job),
    ),
    deliveries=(
        DeliveryRendererDefinition("registration.review_request", deliver_review),
        DeliveryRendererDefinition("registration.review_update", deliver_review),
        DeliveryRendererDefinition("registration.log_approved", deliver_log),
        DeliveryRendererDefinition("registration.log_rejected", deliver_log),
        DeliveryRendererDefinition("registration.member_approved", deliver_dm),
        DeliveryRendererDefinition("registration.member_rejected", deliver_dm),
    ),
)
